name: File Check

on:
  push:
    branches: [main]

jobs:
  setup-infra:
    runs-on: ubuntu-latest
    steps:   
      - name: Create argocd-values.yaml from secret
        run: echo "${{ secrets.ARGO_VALUES }}" > argocd-values.yaml

      - name: ğŸ” Print argocd-values.yaml
        run: |
          echo "===== argocd-values.yaml ë‚´ìš© ====="
          cat argocd-values.yaml
